version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
      - DYNAMODB_SHARE_DB=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh:ro"
      - "./cfn:/etc/localstack/cfn:ro"
